"""Command line interface."""

from __future__ import annotations

import argparse
import asyncio
import sys
from datetime import date
from pathlib import Path

from . import config as config_module
from .config import INTERVAL_PRESETS, ConfigError
from .flow import Flow
from .notifier import TelegramError, check_bot, check_chat, recent_chat_ids
from .parser import Parser, select
from .watcher import Watcher, log

TEMPLATE = '''# {name}
# Generated by `slotwatcher setup`. Docs: https://github.com/amndrd/slot-watcher-bot

[telegram]
token = {token}
chat_id = {chat_id}

[watch]
interval = "{interval}"   # 30sec | 1min | 2min | 5min
scope = "{scope}"{scope_extra}
desktop_notifications = true

[site]
name = "{name}"
url = "{url}"

# Steps taken to reach the page that lists availability.
# Run `slotwatcher dump -c {filename}` to see what the bot ends up reading.
{steps}
[parse]
# Text that marks a date as unavailable (case-insensitive).
full_markers = {full_markers}
# A date is considered free when times like "09:00" appear under it.
require_times = true
date_order = "dmy"        # dmy (31/12/2026) | mdy | ymd
'''

BLANK_STEPS = """# No steps needed if the URL above already shows availability.
# Otherwise add steps, for example:
#
# [[site.steps]]
# action = "click"
# selector = "button#make-appointment"
# navigates = true
"""

ACT_STEPS = '''[[site.steps]]
action = "click"
selector = "button[data-target='#idModal']"

[[site.steps]]
action = "fill"
selector = "#ExpirationDate"
value = "01/01/2030"          # <- your ID card expiry date

[[site.steps]]
action = "check"
selector = "#defaultCheck1"

[[site.steps]]
action = "click"
selector = "#btnConfirmID"
navigates = true

[[site.steps]]
action = "click_in"
container = "form"
contains = "Cat. B - AM - A1 - A2 - A"
selector = "input[type=submit]"
navigates = true

'''


def _ask(prompt, default=None, required=True):
    suffix = f" [{default}]" if default else ""
    while True:
        answer = input(f"{prompt}{suffix}: ").strip()
        if answer:
            return answer
        if default is not None:
            return default
        if not required:
            return ""
        print("  (required)")


def _choose(prompt, options):
    print(f"\n{prompt}")
    for i, (label, description) in enumerate(options, 1):
        print(f"  {i}) {label:<10} {description}")
    while True:
        raw = input(f"Choice [1-{len(options)}]: ").strip()
        if raw.isdigit() and 1 <= int(raw) <= len(options):
            return options[int(raw) - 1][0]
        print("  Please pick a number from the list.")


def cmd_setup(args):
    print("\n  slot-watcher-bot — setup\n" + "─" * 40)

    print("\nStep 1 — Telegram bot")
    print("  Open Telegram, talk to @BotFather, send /newbot, and copy the token.")
    token = _ask("Bot token (leave empty to skip Telegram)", required=False)

    username = chat_id = None
    if token:
        try:
            username = check_bot(token)
            print(f"  Connected to @{username}")
        except TelegramError as exc:
            print(f"  That token was rejected: {exc}")
            return 1

        print("\nStep 2 — Where should alerts go?")
        print(f"  Send any message to @{username} in Telegram now, then press Enter.")
        input("  Press Enter once you've sent it... ")
        try:
            chats = recent_chat_ids(token)
        except TelegramError as exc:
            print(f"  Could not read updates: {exc}")
            chats = {}
        if chats:
            items = list(chats.items())
            for i, (cid, name) in enumerate(items, 1):
                print(f"  {i}) {name} (id {cid})")
            raw = input(f"Choice [1-{len(items)}, or paste an id]: ").strip()
            chat_id = items[int(raw) - 1][0] if raw.isdigit() and 1 <= int(raw) <= len(items) else raw
        else:
            print("  No recent chats found.")
            chat_id = _ask("  Paste your chat id manually")
        try:
            who = check_chat(token, chat_id)
            print(f"  Alerts will go to: {who}")
        except TelegramError as exc:
            print(f"  Could not reach that chat: {exc}")
            return 1

    print("\nStep 3 — How often to check?")
    interval = _choose("Checking too often can get you rate-limited.", [
        ("30sec", "aggressive — only for slots that vanish in seconds"),
        ("1min", "fast"),
        ("2min", "recommended"),
        ("5min", "gentle"),
    ])

    print("\nStep 4 — The site to watch")
    name = _ask("A name for this watch", default="My booking site")
    url = _ask("URL of the booking page")

    template = _choose("Start from:", [
        ("blank", "the URL already shows availability"),
        ("act", "example: ACT Belgium driving theory exam"),
    ])

    print("\nStep 5 — Which dates?")
    scope = _choose("Narrow it down, or take anything:", [
        ("all", "any available date (recommended)"),
        ("month", "one specific month"),
        ("days", "specific days of one month"),
    ])
    scope_extra = ""
    if scope in {"month", "days"}:
        year = _ask("Year", default=str(date.today().year))
        month = _ask("Month (1-12)", default=str(date.today().month))
        scope_extra = f"\nyear = {year}\nmonth = {month}"
        if scope == "days":
            days = _ask("Days, comma separated (e.g. 8,9,10)")
            parsed = [d.strip() for d in days.split(",") if d.strip().isdigit()]
            scope_extra += f"\ndays = [{', '.join(parsed)}]"

    out = Path(args.output).expanduser()
    inline = args.inline_secrets
    body = TEMPLATE.format(
        name=name,
        url=url,
        interval=interval,
        scope=scope,
        scope_extra=scope_extra,
        filename=out.name,
        steps=ACT_STEPS if template == "act" else BLANK_STEPS,
        full_markers='["Volzet", "Complet", "Full", "Fully booked"]',
        token=f'"{token}"' if (token and inline) else '"env:TELEGRAM_TOKEN"',
        chat_id=f'"{chat_id}"' if (chat_id and inline) else '"env:TELEGRAM_CHAT_ID"',
    )
    if out.exists() and not args.force:
        print(f"\n{out} already exists. Re-run with --force to overwrite.")
        return 1
    out.write_text(body)
    print(f"\nWrote {out}")

    if token and not inline:
        print("\nYour token stays out of the file. Add these to your shell:\n")
        print(f"  export TELEGRAM_TOKEN='{token}'")
        print(f"  export TELEGRAM_CHAT_ID='{chat_id}'")
    elif inline:
        print("\n  Secrets were written into the file — never commit it to a public repo.")

    print(f"""
Next:
  slotwatcher check -c {out}          validate the config
  slotwatcher dump  -c {out}          see what the bot reads
  slotwatcher once  -c {out}          one check, no notifications
  slotwatcher run   -c {out}          start watching
""")
    return 0


def _load(args):
    return config_module.load(args.config)


def cmd_check(args):
    cfg = _load(args)
    print(f"Config     : {cfg.path}")
    print(f"Site       : {cfg.name}")
    print(f"URL        : {cfg.url}")
    print(f"Steps      : {len(cfg.steps)}")
    for i, step in enumerate(cfg.steps, 1):
        print(f"   {i}. {step.describe()}" + ("  (navigates)" if step.navigates else ""))
    print(f"Looking for: {cfg.watch.describe()}")
    print(f"Interval   : {cfg.watch.interval}s")
    print(f"Telegram   : ", end="")
    if not cfg.has_telegram:
        print("not configured (desktop notifications only)")
    else:
        try:
            print(f"@{check_bot(cfg.telegram_token)} → {check_chat(cfg.telegram_token, cfg.telegram_chat_id)}")
        except TelegramError as exc:
            print(f"ERROR — {exc}")
            return 1
    print("\nConfig is valid.")
    return 0


def cmd_test_telegram(args):
    cfg = _load(args)
    if not cfg.has_telegram:
        print("Telegram is not configured in this file.")
        return 1
    watcher = Watcher(cfg)
    ok = watcher.notifier.send(
        "🧪 <b>[TEST] slot-watcher-bot</b>\n\n"
        f"Watching: {cfg.name}\n"
        "No slot was found — this is just a delivery test.\n\n"
        "A real alert looks like this:\n"
        "🚨 <b>SLOT AVAILABLE</b>\n"
        "📅 <b>08/09/2026</b> — 07:00, 09:00"
    )
    return 0 if ok else 1


def cmd_dump(args):
    cfg = _load(args)
    flow = Flow(cfg, log, debug_dir=cfg.path.parent / ".debug")
    text = asyncio.run(flow.fetch_text())
    parser = Parser(cfg.parse)
    everything = parser.parse(text)
    matching = select(everything, cfg.watch)

    print("\n" + "=" * 60 + "\nPAGE TEXT THE BOT READS\n" + "=" * 60)
    trimmed = parser._trim(text)
    print(trimmed[:args.limit] + ("\n... (truncated)" if len(trimmed) > args.limit else ""))
    print("\n" + "=" * 60 + "\nDETECTED AS AVAILABLE\n" + "=" * 60)
    if not everything:
        print("Nothing. Either everything is booked, or [parse] needs adjusting:")
        print("  - is date_order right for how dates are printed above?")
        print("  - do full_markers match the site's 'fully booked' wording?")
    for slot in everything:
        mark = "→" if slot in matching else " "
        print(f" {mark} {slot.describe()}")
    if everything and not matching:
        print(f"\nNone match [watch] scope ({cfg.watch.describe()}).")
    return 0


def cmd_once(args):
    cfg = _load(args)
    status, _ = asyncio.run(Watcher(cfg, dry_run=True).check_once())
    print(f"Result: {status}")
    return 0


def cmd_run(args):
    cfg = _load(args)
    try:
        asyncio.run(Watcher(cfg).run())
    except KeyboardInterrupt:
        print("\nStopped.")
    return 0


def build_parser():
    parser = argparse.ArgumentParser(
        prog="slotwatcher",
        description="Watch any booking site for free slots and get a Telegram alert.",
    )
    sub = parser.add_subparsers(dest="command")

    setup = sub.add_parser("setup", help="interactive first-time setup")
    setup.add_argument("-o", "--output", default="config.toml")
    setup.add_argument("--force", action="store_true", help="overwrite an existing file")
    setup.add_argument("--inline-secrets", action="store_true",
                       help="write the token into the file instead of using env vars")
    setup.set_defaults(func=cmd_setup)

    for name, func, help_text in [
        ("check", cmd_check, "validate a config file"),
        ("dump", cmd_dump, "show the page text and what is detected"),
        ("once", cmd_once, "run a single check without notifying"),
        ("run", cmd_run, "watch continuously"),
        ("test-telegram", cmd_test_telegram, "send a test message"),
    ]:
        p = sub.add_parser(name, help=help_text)
        p.add_argument("-c", "--config", default="config.toml")
        if name == "dump":
            p.add_argument("--limit", type=int, default=4000)
        p.set_defaults(func=func)

    return parser


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    if not getattr(args, "func", None):
        parser.print_help()
        return 0
    try:
        return args.func(args)
    except ConfigError as exc:
        print(f"\nConfiguration problem:\n  {exc}\n", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        print("\nCancelled.")
        return 130
